name: Ramani Enterprises
favicon: null
layout_spectrum: 0.7741566093172878
typography_spectrum: 0.32151572965085506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03442889521829784
  lightness: 0.11625729082152247
  saturation: 0.3685307695996016
  rhythmicContrast: 0.18609806918539107
purpose: []
